spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Haybu/temp-config-repo.git
#        native:
#          search-locations: file://${user.home}/Workspaces/github/Haybu/barood/config-repo
#  profiles:
#    active: native

server:
  port: 8888

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: cloud

server:
  port: 8080

# You can define a user-defined-service and bind it to this config server
# so you can bind to it
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.registry-service.credentials.uri}